create extension if not exists pg_trgm;

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  key text not null unique,
  owner text,
  status text default 'Planning',
  description text,
  start_date date,
  deadline date,
  due date,
  progress integer default 0,
  members integer default 0,
  database_name text,
  database_plan text,
  account_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  search_document tsvector
);

create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  role text,
  email text,
  phone text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  search_document tsvector
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  project_id bigint references public.projects(id) on delete cascade,
  title text not null,
  type text default 'Task',
  priority text default 'Medium',
  status text default 'To Do',
  assignee text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  search_document tsvector
);

create table if not exists public.subtasks (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  task_id bigint references public.tasks(id) on delete cascade,
  title text not null,
  status text,
  priority text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  search_document tsvector
);

create or replace function public.workspace_search_document_project()
returns trigger
language plpgsql
as $$
begin
  new.search_document :=
    setweight(to_tsvector('english', coalesce(new.name, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(new.key, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(new.owner, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(new.status, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(new.description, '')), 'C') ||
    setweight(to_tsvector('english', coalesce(new.due::text, '')), 'D') ||
    setweight(to_tsvector('english', coalesce(new.start_date::text, '')), 'D') ||
    setweight(to_tsvector('english', coalesce(new.deadline::text, '')), 'D');
  return new;
end;
$$;

create or replace function public.workspace_search_document_employee()
returns trigger
language plpgsql
as $$
begin
  new.search_document :=
    setweight(to_tsvector('english', coalesce(new.name, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(new.role, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(new.email, '')), 'C') ||
    setweight(to_tsvector('english', coalesce(new.phone, '')), 'D');
  return new;
end;
$$;

create or replace function public.workspace_search_document_task()
returns trigger
language plpgsql
as $$
begin
  new.search_document :=
    setweight(to_tsvector('english', coalesce(new.title, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(new.type, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(new.status, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(new.priority, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(new.assignee, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(new.project_id::text, '')), 'D');
  return new;
end;
$$;

create or replace function public.workspace_search_document_subtask()
returns trigger
language plpgsql
as $$
begin
  new.search_document :=
    setweight(to_tsvector('english', coalesce(new.title, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(new.task_id::text, '')), 'D');
  return new;
end;
$$;

drop trigger if exists workspace_search_document_project on public.projects;
create trigger workspace_search_document_project
before insert or update on public.projects
for each row execute function public.workspace_search_document_project();

drop trigger if exists workspace_search_document_employee on public.employees;
create trigger workspace_search_document_employee
before insert or update on public.employees
for each row execute function public.workspace_search_document_employee();

drop trigger if exists workspace_search_document_task on public.tasks;
create trigger workspace_search_document_task
before insert or update on public.tasks
for each row execute function public.workspace_search_document_task();

drop trigger if exists workspace_search_document_subtask on public.subtasks;
create trigger workspace_search_document_subtask
before insert or update on public.subtasks
for each row execute function public.workspace_search_document_subtask();

alter table public.projects enable row level security;
alter table public.employees enable row level security;
alter table public.tasks enable row level security;
alter table public.subtasks enable row level security;

drop policy if exists projects_owner_access on public.projects;
create policy projects_owner_access on public.projects
for all
using (auth.uid() = owner_id)
with check (auth.uid() = owner_id);

drop policy if exists employees_owner_access on public.employees;
create policy employees_owner_access on public.employees
for all
using (auth.uid() = owner_id)
with check (auth.uid() = owner_id);

drop policy if exists tasks_owner_access on public.tasks;
create policy tasks_owner_access on public.tasks
for all
using (auth.uid() = owner_id)
with check (auth.uid() = owner_id);

drop policy if exists subtasks_owner_access on public.subtasks;
create policy subtasks_owner_access on public.subtasks
for all
using (auth.uid() = owner_id)
with check (auth.uid() = owner_id);
