create table if not exists public.project_members (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  project_id bigint not null references public.projects(id) on delete cascade,
  employee_id bigint references public.employees(id) on delete set null,
  name text not null,
  role text,
  email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.project_members enable row level security;

drop policy if exists project_members_owner_access on public.project_members;
create policy project_members_owner_access on public.project_members
for all
using (auth.uid() = owner_id)
with check (auth.uid() = owner_id);
